BROKER_HOST = "172.17.0.1"
BROKER_PORT = 5672
BROKER_USER = "code_runner"
BROKER_PASSWORD = "yeeyeeasshaircut"

CELERY_IMPORTS = ("app.workers.tasks", )
BROKER_URL = f'pyamqp://{BROKER_USER}:{BROKER_PASSWORD}@{BROKER_HOST}:{BROKER_PORT}//'
CELERY_RESULT_BACKEND = 'rpc://'
# BROKER_HEARTBEAT=10000
