import os

env = os.environ

ENV = env.get('FLASK_ENV', 'production')
DATABASE_USERNAME = env.get('DATABASE_USERNAME')
DATABASE_PASSWORD = env.get('DATABASE_PASSWORD')
DATABASE_HOST = env.get('DATABASE_HOST')
DATABASE_NAME = env.get('DATABASE_NAME')
SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOST}/" + \
                          f"{DATABASE_NAME}"
SQLALCHEMY_ECHO = True if ENV == 'development' else False
SQLALCHEMY_TRACK_MODIFICATIONS = False
CELERY_BROKER_HOST = env.get('CELERY_BROKER_HOST')
CELERY_BROKER_PORT = env.get('CELERY_BROKER_PORT')
CELERY_BROKER_USER = env.get('CELERY_BROKER_USER')
CELERY_BROKER_PASSWORD = env.get('CELERY_BROKER_PASSWORD')